backend:
  name: github
  repo: YOUR_GITHUB_USERNAME/YOUR_REPOSITORY_NAME # IMPORTANT: Replace with your repo path
  branch: main # or master

media_folder: "assets/images" # Where media files will be stored
public_folder: "/assets/images" # The src attribute for uploaded media

collections:
  - name: "pages"
    label: "Page Content"
    files:
      - file: "_data/main.yml"
        label: "Homepage Content"
        name: "homepage"
        fields:
          - { label: "Hero Title", name: "hero_title", widget: "string" }
          - { label: "Hero Subtitle", name: "hero_subtitle", widget: "string" }
          - { label: "About Me Narrative", name: "about_narrative", widget: "markdown" }
          - { label: "Profile Picture", name: "profile_picture", widget: "image" }
          - { label: "Resume File", name: "resume_pdf", widget: "file" }
          - { label: "Contact Email", name: "contact_email", widget: "string" }
          - { label: "LinkedIn URL", name: "linkedin_url", widget: "string" }
          - { label: "GitHub URL", name: "github_url", widget: "string" }

  - name: "projects"
    label: "Projects"
    folder: "_projects/"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Tools Used (comma separated)", name: "tools", widget: "string" }
      - { label: "Summary", name: "summary", widget: "text" }
      - { label: "Full Description (for modal)", name: "description", widget: "markdown" }

  - name: "experience"
    label: "Experience"
    folder: "_experience/"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Company", name: "company", widget: "string" }
      - { label: "Job Title", name: "title", widget: "string" }
      - { label: "Dates", name: "dates", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Order", name: "order", widget: "number", value_type: "int" }

  - name: "education"
    label: "Education"
    folder: "_education/"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Institution", name: "institution", widget: "string" }
      - { label: "Degree", name: "degree", widget: "string" }
      - { label: "Dates", name: "dates", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Order", name: "order", widget: "number", value_type: "int" }

  - name: "gallery"
    label: "Gallery"
    folder: "_gallery/"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Caption", name: "caption", widget: "string" }

  - name: "blog"
    label: "Blog"
    folder: "_posts/"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }
